# Generated by Django 5.2 on 2026-08-05 21:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pet_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='communitypost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vaccination',
            options={'ordering': ['next_due_date']},
        ),
        migrations.AlterModelOptions(
            name='vetvisit',
            options={'ordering': ['-visit_date']},
        ),
        migrations.AddField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vetvisit',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='app.pet'),
        ),
        migrations.AlterField(
            model_name='vetvisit',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_visits', to='app.pet'),
        ),
        migrations.AlterField(
            model_name='vetvisit',
            name='reason',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='CaregiverAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View only'), ('edit', 'Can edit')], default='view', max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_pets', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregivers', to='app.pet')),
            ],
            options={
                'verbose_name_plural': 'Caregiver access',
                'unique_together': {('pet', 'caregiver')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('document_type', models.CharField(choices=[('lab_result', 'Lab result'), ('vet_report', 'Vet report'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='pet_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.pet')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once daily'), ('twice_daily', 'Twice daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('as_needed', 'As needed'), ('custom', 'Custom')], default='once_daily', max_length=20)),
                ('custom_schedule_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_dose_date', models.DateField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='app.pet')),
            ],
            options={
                'ordering': ['next_dose_date'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('lb', 'lbs'), ('kg', 'kg')], default='lb', max_length=2)),
                ('recorded_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='app.pet')),
            ],
            options={
                'ordering': ['-recorded_date'],
            },
        ),
        migrations.DeleteModel(
            name='FamilyMembers',
        ),
    ]
