# Generated by Django 5.2 on 2026-08-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_comment_options_alter_communitypost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name']},
        ),
    ]
