# Generated by Django 5.2 on 2026-08-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetvisit',
            name='reason',
            field=models.CharField(max_length=25),
        ),
    ]
