# Generated by Django 5.2 on 2026-08-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_vetvisit_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vetvisit',
            name='follow_up_completed',
            field=models.BooleanField(default=False),
        ),
    ]
